services:
  asset-upnp:
    image: "psweetie/asset-upnp"
    container_name: asset-upnp
    volumes:
    - "./data:/data"
    - "./media:/media:ro"
    network_mode: host
    restart: unless-stopped
    init: true
